### ISSUE TITLE
Compiling on Visual Studio 2010, developing your netcode.

### ISSUE THREAD

**Issue by BevP90** [alexsharoff/pcsx2#4]
Hey Alex,

Just wanted to know how you were compiling your build, I've tried VS 2010 but it keeps throwing up errors when building. I've been able to make changes to the GUI but it still will not build. The guys over at the Capnet Club Discord now stand at 600 members and we're looking to develop your netcode, I'm looking to find someone who codes C++ and will being paying them for their work. What do you recommend? If nothing I'd at least like to invite you to play some matches with us in the Discord. Link with the video trailer below.
Thanks,
 Bev (Admin of Capnet Club)

![Mockup](https://user-images.githubusercontent.com/29954013/77808147-31b18b80-7082-11ea-92c3-21976a1b637d.png)

[https://www.youtube.com/watch?v=CvPKyxefQIQ](url)

**Comment by alexsharoff** [comment]
Please specify exactly what you're doing and what errors you are receiving, otherwise I won't be able to help.
But judging by the attached screenshot, you're all set?

**Comment by BevP90** [comment]
@alexsharoff I've had 7 errors when trying to compile it. I'm also still looking for yourself or someone to improve on the netcode. We're putting together a money pot over at Capnet Club.

**Comment by alexsharoff** [comment]
@BevP90 Please specify error messages you're getting. I cannot reproduce any errors on my end.

**Comment by BevP90** [comment]
@alexsharoff Would you be able to join the Discord to chat? That way we can discuss what we're looking to do.

**Comment by BevP90** [comment]
I've uninstalled Visual Studio 2010 as I don't know how to fix the errors. Still looking to get something working still and make improvements.
Edit: Would you be able to improve your netcode?

**Comment by alexsharoff** [comment]
Without any concrete information I won't be able to help.
Between my job and GGXXACPR rollback patch I'm working on currently, this project is not a priority at all.
