### ISSUE TITLE
Playing with 3 players.

### ISSUE THREAD

**Issue by Uka-Uka** [alexsharoff/pcsx2#5]
Hello, Alex! How are you? I hope all is well.

I was really happy when I new replies by you on the issues section, and I hope one day you'll be working on improving the PCSX2 net code.

I just wanted you if possible to guide me on how we can play with 3 players, I know that this feature was first time introduced on SmileTheory version but I can't contact him at all, so I thought maybe you can help with this.

**Comment by alexsharoff** [comment]
Unfortunately, this project wasn't designed to support 3 players (or more). I don't have any incentive to continue developing this project, but I'm still glad to see it being used in the wild.

Just out of curiosity: what game with 3 player support do you have in mind?

**Comment by Uka-Uka** [comment]
Oh sorry for the long silence! Anyway, all PCSX2 community appreciates you and your work that gave us an opportunity to play our favorite games online.

As for the game, we were aiming to play some games of WWE series like HCTP and SVR 2008

By the way, I have a question if you don't mind, how is input delay supposed to be adjusted? I know that your build adjusts input delay automatically but that feature got removed later by SmileTheory, so I just wanted to know if there a method to follow to set that value properly.

**Comment by alexsharoff** [comment]
If SmileTheory's fork requires you to manually enter input delay, then a good estimate would be (average ping between players / 33,333)

**Comment by Uka-Uka** [comment]
aha, I see! that got something to do with PS2 games being played at 30fps internally. thanks for the info.
